{{ range .Values.volumeSnapshotClasses }}
---
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: {{ .name | default "default" }}
{{- if .isDefault }}
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
{{- end }}
driver: {{ .driver | default "driver.example.com" }}
deletionPolicy: {{ .deletionPolicy | default "Delete" }}
parameters: {{ toYaml (.parameters | default dict) | nindent 2 }}
---
{{ end }}